# Do not change anything here unless you fully understand logging and HydroCNHS
# structure. All user settings for the HydroCNHS system should be done in
# Config.yaml.

version: 1
formatters:
  brief:
    format: '%(name)s %(message)s'
  simple:
    format: '[%(asctime)s] %(name)s [%(levelname)s] %(message)s'
    datefmt: '%m/%d %I:%M:%S'
  simple_with_year:
    format: '[%(asctime)s] %(name)s [%(levelname)s] %(message)s'
    datefmt: '%Y/%m/%d %I:%M:%S'

handlers:                     # Set console and log file handlers.
  console:                    # Do not delete this!
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple         # Output format brief or simple
    stream: ext://sys.stdout
  file:                       # Do not delete this!
    class : logging.handlers.RotatingFileHandler
    formatter: simple_with_year   # Output format brief or simple
    filename: HydroCNHS.log
    maxBytes: 1024
    backupCount: 3

loggers:
  HydroCNHS:                  # Logger name. Do not not modify this! 
    level: INFO               # Msg level ['DEBUG', 'INFO', 'WARNING', 'ERROR']
    handlers: [console, file] # Do not change this!
    propagate: no
# Root logger. If there is not specific logger is assign, then system will
# default root logger.
root:                         
  level: DEBUG
  handlers: [console]